server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 192.168.225.128:8848
    gateway:
      routes:
        - id: search-service
          uri: lb://searchservice
          predicates:
            - Path=/hotel/search/**
        - id: admin-service
          uri: lb://adminservice
          predicates:
            - Path=/hotel/admin/**
