server:
  port: 8089
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.225.128 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: xmb
    password: 123456
    virtual-host: hotel
  application:
    name: searchservice
  cloud:
    nacos:
      server-addr: 192.168.225.128:8848
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: HH:mm:ss:SSS
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cn.xmb.hotel.pojo