server:
  port: 8030
spring:
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: 192.168.225.128:8848
  rabbitmq:
    host: 192.168.225.128
    port: 5672
    username: xmb
    password: 123456
    virtual-host: hotel
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson: # 设置页面显示时间时区和格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:  # 设置日志配置
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS


